name: Test on Push

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.26'

    - name: Run mcp-servers/ygo-db tests
      run: |
        go test -v ./...
      working-directory: mcp-servers/ygo-db
